In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/titanic/train.csv
/kaggle/input/competitions/titanic/test.csv
/kaggle/input/competitions/titanic/gender_submission.csv

In [2]:
train_data = pd.read_csv("/kaggle/input/competitions/titanic/train.csv")
train_data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [3]:
test_data = pd.read_csv("/kaggle/input/competitions/titanic/test.csv")
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [4]:
women = train_data.loc[train_data.Sex == "female"]["Survived"]
w_rate = sum(women)/len(women)
print("% of women survived: ",w_rate*100)

% of women survived:  74.20382165605095

In [5]:
men = train_data.loc[train_data.Sex == "male"]["Survived"]
m_rate = sum(men)/len(men)
print("% of men survived: ",m_rate*100)

% of men survived:  18.890814558058924

In [6]:
submission = pd.read_csv("/kaggle/input/competitions/titanic/gender_submission.csv")
merged_data = pd.merge(submission,test_data,on = "PassengerId")
women = merged_data.loc[merged_data.Sex == "female","Survived"]
print("No.of women: ",len(women))
print("No.of women survived: ",sum(women))

No.of women:  152
No.of women survived:  152

In [7]:
men = merged_data.loc[merged_data.Sex == "male","Survived"]
print("No.of men: ",len(men))
print("No.of men survived: ",sum(men))

No.of men:  266
No.of men survived:  0

In [8]:
from sklearn.ensemble import RandomForestClassifier

y = train_data["Survived"]

features = ["Pclass","Sex","SibSp","Parch"]
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

model = RandomForestClassifier(n_estimators=100,max_depth=5,random_state = 1)
model.fit(X,y)

predictions = model.predict(X_test)
output = pd.DataFrame({"PassengerId":test_data.PassengerId,"Survived":predictions})
output.to_csv("submission.csv",index=False)

print("Submission is successfully saved!")

Submission is successfully saved!